/*
  Page transitions between the gate and the three universes (07 §4.2).
  Global on purpose: view-transition pseudo-elements and transition types
  can't live in a CSS module. Classes come from <UniversePage> (React
  <ViewTransition enter/exit> keyed by the Link transitionTypes set in
  model.ts), names from hero-morph.ts, the switcher and the header.

  Only transform + opacity. Reduced motion: nothing moves (also covered by
  the global guard). No View Transitions support: plain, instant navigation.
*/

// Inlined by <UniversePage> as a hoisted, deduped <style> (no extra
// render-blocking stylesheet request).
export const UNIVERSE_TRANSITIONS_CSS = `::view-transition{pointer-events:none}::view-transition-group(gp-site-header),::view-transition-group(gp-switch-bar){animation:none;z-index:40}::view-transition-old(gp-site-header),::view-transition-old(gp-switch-bar){display:none}::view-transition-new(gp-site-header),::view-transition-new(gp-switch-bar){animation:none}::view-transition-group(gp-switch-ind){z-index:41;animation-duration:380ms;animation-timing-function:cubic-bezier(0.2,0.8,0.2,1)}::view-transition-old(.gp-forward),::view-transition-old(.gp-back){animation:gp-vt-fade-out 160ms linear both,gp-vt-to-start 260ms cubic-bezier(0.4,0,1,1) both}::view-transition-new(.gp-forward),::view-transition-new(.gp-back){animation:gp-vt-fade-in 220ms linear 40ms both,gp-vt-from-end 360ms cubic-bezier(0.2,0.8,0.2,1) both}::view-transition-old(.gp-back){animation-name:gp-vt-fade-out,gp-vt-to-end}::view-transition-new(.gp-back){animation-name:gp-vt-fade-in,gp-vt-from-start}html[dir="rtl"]::view-transition-old(.gp-forward){animation-name:gp-vt-fade-out,gp-vt-to-end}html[dir="rtl"]::view-transition-new(.gp-forward){animation-name:gp-vt-fade-in,gp-vt-from-start}html[dir="rtl"]::view-transition-old(.gp-back){animation-name:gp-vt-fade-out,gp-vt-to-start}html[dir="rtl"]::view-transition-new(.gp-back){animation-name:gp-vt-fade-in,gp-vt-from-end}::view-transition-old(.gp-gate){animation:gp-vt-fade-out 180ms linear both}::view-transition-new(.gp-gate){animation:gp-vt-rise 380ms cubic-bezier(0.2,0.8,0.2,1) 90ms both}::view-transition-group(.gp-hero){z-index:42;animation-duration:520ms;animation-timing-function:cubic-bezier(0.2,0.8,0.2,1)}::view-transition-old(.gp-hero),::view-transition-new(.gp-hero){height:100%;object-fit:cover}::view-transition-old(.gp-hero){animation:gp-vt-fade-out 240ms linear both}::view-transition-new(.gp-hero){animation:gp-vt-fade-in 260ms linear 60ms both}@keyframes gp-vt-to-start{to{transform:translateX(-32px)}}@keyframes gp-vt-to-end{to{transform:translateX(32px)}}@keyframes gp-vt-from-end{from{transform:translateX(48px)}}@keyframes gp-vt-from-start{from{transform:translateX(-48px)}}@keyframes gp-vt-fade-in{from{opacity:0}}@keyframes gp-vt-fade-out{to{opacity:0}}@keyframes gp-vt-rise{from{opacity:0;transform:translateY(16px)}}@media (prefers-reduced-motion:reduce){::view-transition-group(*),::view-transition-old(*),::view-transition-new(*){animation:none !important}}`;
