import createMiddleware from "next-intl/middleware";
import { NextResponse, type NextRequest } from "next/server";
import { routing } from "./i18n/routing";

const intlMiddleware = createMiddleware(routing);

const LOCALES = routing.locales as readonly string[];

// Next 16 renamed middleware.ts -> proxy.ts (Node.js runtime).
//
// /contact is the business-card QR landing page. It is served as plain static
// HTML (public/qr/<lang>.html, generated by scripts/build-qr-contact.mjs) —
// zero JavaScript, inline CSS — so it loads instantly on mobile data.
// Public URLs are REWRITTEN (a redirect would cost an extra round trip).
const CONTACT_PATH = /^\/(?:(fr|ar|en)\/)?contact$/;

function detectLocale(req: NextRequest): string {
  const cookie = req.cookies.get("NEXT_LOCALE")?.value;
  if (cookie && LOCALES.includes(cookie)) return cookie;
  const accept = req.headers.get("accept-language") ?? "";
  for (const part of accept.split(",")) {
    const [tag, q] = part.trim().split(";");
    if (q && /q=0(\.0*)?$/.test(q.trim())) continue;
    const lang = tag.slice(0, 2).toLowerCase();
    if (LOCALES.includes(lang)) return lang;
  }
  return routing.defaultLocale;
}

export default function proxy(req: NextRequest) {
  const match = req.nextUrl.pathname.match(CONTACT_PATH);
  if (match) {
    const explicit = match[1];
    const url = req.nextUrl.clone();
    url.pathname = `/qr/${explicit ?? detectLocale(req)}.html`;
    const res = NextResponse.rewrite(url);
    // Remember an explicitly chosen language so the "website" button (and a
    // later bare /contact visit) stays in it instead of being re-detected.
    if (explicit) res.cookies.set("NEXT_LOCALE", explicit, { path: "/", sameSite: "lax" });
    return res;
  }
  return intlMiddleware(req);
}

export const config = {
  matcher: [
    "/((?!api|admin|_next|_vercel|.*\\..*).*)",
    "/",
  ],
};
